import type { KeyboardLocaleKey } from "./types.ts";

/**
 * US QWERTY legends by Set 1 make-code (hex) — the scancode space
 * [Keyboard.json](resources/Keyboard.json) is written in.
 *
 * `letter` marks the keys Caps Lock swaps against Shift. It replaces the old
 * "scancode sits in a letter row" test, which was a US assumption: on the
 * Finnish layout `1A`/`27`/`28` are `å`/`ö`/`ä` (letters) while `2B` is `'`
 * (not one), so which scancodes are letters has to come from the locale.
 */
export const US_KEYS: Record<string, KeyboardLocaleKey> = {
  "29": { base: "`", shift: "~" },
  "02": { base: "1", shift: "!" },
  "03": { base: "2", shift: "@" },
  "04": { base: "3", shift: "#" },
  "05": { base: "4", shift: "$" },
  "06": { base: "5", shift: "%" },
  "07": { base: "6", shift: "^" },
  "08": { base: "7", shift: "&" },
  "09": { base: "8", shift: "*" },
  "0A": { base: "9", shift: "(" },
  "0B": { base: "0", shift: ")" },
  "0C": { base: "-", shift: "_" },
  "0D": { base: "=", shift: "+" },
  "0E": { base: "⌫", shift: "⌫" },
  "0F": { base: "Tab", shift: "Tab" },
  "10": { base: "q", shift: "Q", letter: true },
  "11": { base: "w", shift: "W", letter: true },
  "12": { base: "e", shift: "E", letter: true },
  "13": { base: "r", shift: "R", letter: true },
  "14": { base: "t", shift: "T", letter: true },
  "15": { base: "y", shift: "Y", letter: true },
  "16": { base: "u", shift: "U", letter: true },
  "17": { base: "i", shift: "I", letter: true },
  "18": { base: "o", shift: "O", letter: true },
  "19": { base: "p", shift: "P", letter: true },
  "1A": { base: "[", shift: "{" },
  "1B": { base: "]", shift: "}" },
  "2B": { base: "\\", shift: "|" },
  "3A": { base: "Caps", shift: "Caps" },
  "1E": { base: "a", shift: "A", letter: true },
  "1F": { base: "s", shift: "S", letter: true },
  "20": { base: "d", shift: "D", letter: true },
  "21": { base: "f", shift: "F", letter: true },
  "22": { base: "g", shift: "G", letter: true },
  "23": { base: "h", shift: "H", letter: true },
  "24": { base: "j", shift: "J", letter: true },
  "25": { base: "k", shift: "K", letter: true },
  "26": { base: "l", shift: "L", letter: true },
  "27": { base: ";", shift: ":" },
  "28": { base: "'", shift: '"' },
  "1C": { base: "↵", shift: "↵" },
  "2A": { base: "Shift", shift: "Shift" },
  "2C": { base: "z", shift: "Z", letter: true },
  "2D": { base: "x", shift: "X", letter: true },
  "2E": { base: "c", shift: "C", letter: true },
  "2F": { base: "v", shift: "V", letter: true },
  "30": { base: "b", shift: "B", letter: true },
  "31": { base: "n", shift: "N", letter: true },
  "32": { base: "m", shift: "M", letter: true },
  "33": { base: ",", shift: "<" },
  "34": { base: ".", shift: ">" },
  "35": { base: "/", shift: "?" },
  "36": { base: "Shift", shift: "Shift" },
  "1D": { base: "Ctrl", shift: "Ctrl" },
  "E01D": { base: "Ctrl", shift: "Ctrl" },
  "38": { base: "Alt", shift: "Alt" },
  "E038": { base: "Alt", shift: "Alt" },
  "39": { base: "Space", shift: "Space" },
  "E05B": { base: "Win", shift: "Win" },
  "E05C": { base: "Win", shift: "Win" },
  "E05D": { base: "☰", shift: "☰" },
  "E052": { base: "Ins", shift: "Ins" },
  "E053": { base: "Del", shift: "Del" },
  "E047": { base: "Home", shift: "Home" },
  "E04F": { base: "End", shift: "End" },
  "E049": { base: "PgUp", shift: "PgUp" },
  "E051": { base: "PgDn", shift: "PgDn" },
  "E048": { base: "↑", shift: "↑" },
  "E04B": { base: "←", shift: "←" },
  "E050": { base: "↓", shift: "↓" },
  "E04D": { base: "→", shift: "→" },
  "E11D": { base: "Pause", shift: "Pause" },
  "46": { base: "ScLk", shift: "ScLk" },
  "54": { base: "Prt", shift: "Prt" },
  "3B": { base: "F1", shift: "F1" },
  "3C": { base: "F2", shift: "F2" },
  "3D": { base: "F3", shift: "F3" },
  "3E": { base: "F4", shift: "F4" },
  "3F": { base: "F5", shift: "F5" },
  "40": { base: "F6", shift: "F6" },
  "41": { base: "F7", shift: "F7" },
  "42": { base: "F8", shift: "F8" },
  "43": { base: "F9", shift: "F9" },
  "44": { base: "F10", shift: "F10" },
  "57": { base: "F11", shift: "F11" },
  "58": { base: "F12", shift: "F12" },
  "01": { base: "Esc", shift: "Esc" },
  "7D": { base: "⌫", shift: "⌫" },
};
